### PR TITLE
Update to v6.1.4

### PR DESCRIPTION
**Pull request by eriknw**
~~**DO NOT MERGE.** We're making progress, but we need more trial-and-error here on conda-forge.~~

Checklist
* [x] Used a [personal fork of the feedstock to propose changes](https://conda-forge.org/docs/maintainer/updating_pkgs.html#forking-and-pull-requests)
* [x] Bumped the build number (if the version is unchanged)
* [x] Reset the build number to `0` (if the version changed)
* [x] [Re-rendered]( https://conda-forge.org/docs/maintainer/updating_pkgs.html#rerendering-feedstocks ) with the latest `conda-smithy` (Use the phrase <code>@<space/>conda-forge-admin, please rerender</code> in a comment in this PR for automated rerendering)
* [x] Ensured the license file is being packaged.

### CODE REVIEW

**Comment by eriknw** [comment]
@conda-forge-admin, please rerender

**Review by jim22k — APPROVED** [review]
Looks great! Should we wait on the "official" 6.1.4 or build from the beta?

**Comment by eriknw** [comment]
I vote for waiting.  I expect it to be released shortly.

**Comment by jakirkham** [comment]
There is [CFEP 05]( https://github.com/conda-forge/cfep/blob/main/cfep-05.md ), which covers packaging RCs. It could be used to release this if that is of interest

Not that this needs to be done. Just sharing the option exists if desired :)

**Comment by eriknw** [comment]
Thanks for brining that to our attention @jakirkham!  We don't urgently need a release (but if you know anybody who does, let us know!).  We'll talk with Tim Davis tomorrow and will ask when he plans to release 6.1.4.

Tim does often have RCs and appreciates it when downstream users are able to try them.  Perhaps we should build more RCs on conda-forge as a general practice.

**Pull request merged**
