### PR TITLE
Update to version 4.0.1

### PR DESCRIPTION
**Pull request by jim22k**
Checklist
* [x] Used a [personal fork of the feedstock to propose changes](https://conda-forge.org/docs/maintainer/updating_pkgs.html#forking-and-pull-requests)
* [ ] Bumped the build number (if the version is unchanged)
* [x] Reset the build number to `0` (if the version changed)
* [x] [Re-rendered]( https://conda-forge.org/docs/maintainer/updating_pkgs.html#rerendering-feedstocks ) with the latest `conda-smithy` (Use the phrase <code>@<space/>conda-forge-admin, please rerender</code> in a comment in this PR for automated rerendering)
* [ ] Ensured the license file is being packaged.

### CODE REVIEW

**Comment by jim22k** [comment]
@conda-forge-admin, please rerender

**Comment by jakirkham** [comment]
Thanks Jim! 😄

Would you have any interest in being [a maintainer]( https://conda-forge.org/docs/maintainer/updating_pkgs.html ) here as well? If so, please feel free to add yourself to the list at the bottom of the `meta.yaml`. If not, no worries. 🙂

**Comment by jim22k** [comment]
I'm actually already a maintainer 😄

**Comment by jakirkham** [comment]
> I'm actually already a maintainer 😄

Ha! 😂 Sorry for missing that

**Review by jakirkham — APPROVED** [review]

**Pull request merged**
