### PR TITLE
No static

### PR DESCRIPTION
**Pull request by eriknw**
Checklist
* [X] Used a [personal fork of the feedstock to propose changes](https://conda-forge.org/docs/maintainer/updating_pkgs.html#forking-and-pull-requests)
* [X] Bumped the build number (if the version is unchanged)
* [ ] [Re-rendered]( https://conda-forge.org/docs/maintainer/updating_pkgs.html#rerendering-feedstocks ) with the latest `conda-smithy` (Use the phrase <code>@<space/>conda-forge-admin, please rerender</code> in a comment in this PR for automated rerendering)
* [X] Ensured the license file is being packaged.

Let's not build the static library.  See: https://github.com/conda-forge/cfep/blob/master/cfep-18.md

Also, let's tell cmake we're doing a "Release" build.

I received feedback to make these improvements for the LAGraph recipe here: https://github.com/conda-forge/staged-recipes/pull/12391

### CODE REVIEW

**Comment by grlee77** [comment]
Thanks @eriknw. This looks good (pending CI success)

I am not certain if any downstream packages currently depend on the static library. I suppose we can remove it and if there are complaints, add a separate, static package later.

**Comment by eriknw** [comment]
Sounds good.  I believe [grblas](https://github.com/conda-forge/grblas-feedstock) should be fine without the static library.  Even if somebody needs the static library, it should be made available as `graphblas-static`.  See [here](https://github.com/conda-forge/cfep/blob/master/cfep-18.md#implementation).

**Comment by eriknw** [comment]
Shall we merge?  Do we need to re-render first?

@conda-forge-admin, please rerender

**Comment by eriknw** [comment]
Oh, I'm not a maintainer yet, so I don't know if I can initiate a rerender.

**Review by basnijholt — APPROVED** [review]
LGTM, thanks!

**Review by jim22k — APPROVED** [review]

**Pull request merged**
