### PR TITLE
Update to v7.3.0

### PR DESCRIPTION
**Pull request by eriknw**
Checklist
* [x] Used a [personal fork of the feedstock to propose changes](https://conda-forge.org/docs/maintainer/updating_pkgs.html#forking-and-pull-requests)
* [x] Bumped the build number (if the version is unchanged)
* [x] Reset the build number to `0` (if the version changed)
* [x] [Re-rendered]( https://conda-forge.org/docs/maintainer/updating_pkgs.html#rerendering-feedstocks ) with the latest `conda-smithy` (Use the phrase <code>@<space/>conda-forge-admin, please rerender</code> in a comment in this PR for automated rerendering)
* [x] Ensured the license file is being packaged.

### CODE REVIEW

**Comment by eriknw** [comment]
@conda-forge-admin, please rerender

**Comment by eriknw** [comment]
@DrTimothyAldenDavis any idea about the Windows failure here?

https://dev.azure.com/conda-forge/feedstock-builds/_build/results?buildId=589203&view=logs&j=8af117b0-dfa5-5d1c-b02e-a448dd16efdb&t=5255ce7d-8850-5a89-87a7-dc472af37343&l=3924

Sorry for not trying to build one of the betas.

**Comment by DrTimothyAldenDavis** [comment]
No idea.  Maybe the compiler ran out of memory or something?  Can you try building on a single core?

**Comment by eriknw** [comment]
I manually reverted back to vs2017, and we no longer get the error that we see when using vs2019.

conda-forge recently updated to vs2019/vc142 toolchain:
- https://github.com/conda-forge/conda-forge.github.io/issues/1732
- https://github.com/conda-forge/conda-forge-pinning-feedstock/pull/3167

@jakirkham should we continue using vs2017? Should we ping anybody else about the issue we saw in vs2019? This is beyond my expertise, but I generally trust forward compatibility of Microsoft compilers.

**Comment by eriknw** [comment]
YOLO. Let's use vs2017. Merging.

**Comment by DrTimothyAldenDavis** [comment]
Great!  I should probably post a note on SuiteSparse:GraphBLAS about using vscode 2019.  Which version of VS code does that correspond to on this list?  https://code.visualstudio.com/updates/v1_72

**Comment by eriknw** [comment]
> Great! I should probably post a note on SuiteSparse:GraphBLAS about using vscode 2019. Which version of VS code does that correspond to on this list? https://code.visualstudio.com/updates/v1_72

I don't think vs2017 or vs2019 are on that list.  See: https://visualstudio.microsoft.com/vs/older-downloads/

**Comment by DrTimothyAldenDavis** [comment]
Got it.  Have you tried vs2020 or later?  Maybe the bug only appears in vs2019.

**Comment by eriknw** [comment]
Nope, sorry.  I don't think there are many other versions for us to try as part of this CI workflow.

**Comment by jakirkham** [comment]
> I manually reverted back to vs2017, and we no longer get the error that we see when using vs2019.
> 
> conda-forge recently updated to vs2019/vc142 toolchain:
> 
> * [Move to vc142 toolchain on windows conda-forge.github.io#1732](https://github.com/conda-forge/conda-forge.github.io/issues/1732)
> * [move to vs2019/vc142 conda-forge-pinning-feedstock#3167](https://github.com/conda-forge/conda-forge-pinning-feedstock/pull/3167)
> 
> @jakirkham should we continue using vs2017? Should we ping anybody else about the issue we saw in vs2019? This is beyond my expertise, but I generally trust forward compatibility of Microsoft compilers.

Was out when this was asked.

Yes would suggest raising a new issue on this feedstock with relevant details (like logs, snippet of the error, etc.) and ping core.

**Comment by eriknw** [comment]
Thanks @jakirkham. Done: https://github.com/conda-forge/graphblas-feedstock/issues/47

**Comment by h-vetinari** [comment]
> > > > @DrTimothyAldenDavis: Great! I should probably post a note on SuiteSparse:GraphBLAS about using vscode 2019. Which version of VS code does that correspond to on this list? https://code.visualstudio.com/updates/v1_72
> > >
> > > @eriknw: I don't think vs2017 or vs2019 are on that list. See: https://visualstudio.microsoft.com/vs/older-downloads/
> >
> > @DrTimothyAldenDavis: Got it. Have you tried vs2020 or later? Maybe the bug only appears in vs2019.
>
> @eriknw: Nope, sorry. I don't think there are many other versions for us to try as part of this CI workflow.

There's no vs2020. Ignoring ancient history, there's 2015, 2017, 2019, 2022, but in general the numbering scheme is hella confusing, e.g.

| VS year | VS version | Toolchain<br/>version (default)  | MSVC++ version | `_MSC_VER` | version reported<br/>by cl.exe |
|-|-|-|-|-|-|
| 2017 | 15.x | 141 | 14.1x | 191x | 19.1x.yyyyy |
| 2019 | 16.x | 142 | 14.2x | 192x | 19.2x.yyyyy |
| 2022 | 17.x | 143 | 14.3x | 193x | 19.3x.yyyyy |

For each release (each line in the table above has several, roughly x=0..9), the `x` in 14- & 19-versions is always the same; since VS2019 the `x` in the VS version also matches. More [details](https://en.wikipedia.org/wiki/Microsoft_Visual_C%2B%2B#Internal_version_numbering).

PS. Conda-forge doesn't have vs2022 [yet](https://github.com/conda-forge/vc-feedstock/pull/46).

**Pull request merged**
